### ISSUE TITLE
Annotation InheritInject does not pull inherited property

### ISSUE THREAD

**Issue by rescobedo** [Citytechinc/bedrock#13]
Using the InheritInject annotation does not yield the expected inheritance results in a child page where the component has been authored on parent page. 

import com.citytechinc.aem.bedrock.models.annotations.InheritInject
...
@DialogField(fieldLabel = "test", tab = 1, ranking = 1d, required = true)
@TextField
@InheritInject @Default("test label)
String testLabel

Also, the default value is not getting picked up either.

**Comment by michaelhodgdon** [comment]
fixed in 4.0.1
